---
output: 
  html_document2:
    css: style.css
editor_options:
  markdown:
    wrap: 72
---

```{r echo=FALSE, warning=FALSE, }
library(rmarkdown)
library(latex2exp)
library(kableExtra)
```

# Formulas utiles

-   Modelo geométrico desplazado:

    $$
    P(T=t| \theta) = \theta (1 - \theta)^{t-1}
    $$

    $$
    P(T>t| \theta) = (1-\theta)^{t}
    $$

-   Modelo beta geométrico desplazado:

    $$
    \mathbb{P}(T = t \mid \alpha, \beta) = \frac{B(\alpha+1, t+\beta-1)}{B(\alpha, \beta)}
    $$

    $$
    \mathbb{P}(T>t \mid \alpha, \beta) = \frac{B(\alpha, t+\beta)}{B(\alpha, \beta)}
    $$

-   Modelo de Duración Exponencial:

    $$
    P(T \leq t) = 1 - e^{-\lambda t}
    $$

    $$
    P(T > t) = e^{-\lambda t}
    $$

-   Modelo Gamma Exponencial:

    $$
    \mathbb{P}(T \leq t) = 1 - \left(\frac{\alpha}{\alpha + t}\right)^r
    $$

-   Modelo de Duración Weibull:

    $$
    P(T \leq t) = 1 - e^{-\lambda t ^c}
    $$

    $$
    \mathbb{P}(T \leq t \mid \alpha, r, c) = 1 - \left(\frac{\alpha}{\alpha + t^c}\right)^r
    $$

-   Modelo de Conteo:

    $$
    P(N_t=m|\lambda) = \frac{(\lambda t)^m e^{-\lambda t}}{m!}
    $$

-   Modelo Gamma Poisson:

    $$
    \mathbb{P}(N_t = m \mid r, \alpha) = \left( \frac{\alpha}{\alpha+t}\right)^r \left( \frac{t}{\alpha + t}\right)^m \frac{\Gamma(r+m)}{\Gamma(r)m!}
    $$

-   Modelo de elección binomial:

    $$
    P(X_s = x_s|m_s,p_s) = \binom{m_s}{x_s} p_s^{x_s}(1-p_s)^{m_s-x_s}
    $$

-   Modelo Beta Binomial

    $$
    \mathbb{P}(X_s = x_s \mid \alpha, \beta) = \binom{m_s}{x_s} \frac{B(\alpha + x_s, \beta + m_s - x_s)}{B(\alpha,\beta)}
    $$

-   Esperanzas condicionales:

::: {style="overflow-x:auto;"}
| Modelo                     | Distribución Incondicional                    | Distribución Condicional                                  | Esperanza Condicional                                         |
|----------------------------|-----------------------------------------------|-----------------------------------------------------------|----------------------------------------------------------------|
| Modelo de Tiempo Discreto  | $\theta \sim \mathrm{Beta}(\alpha,\beta)$     | $\theta \mid t \sim \mathrm{Beta}(\alpha+1,\ \beta+t)$    | $\mathbb{E}[\theta \mid t] = \dfrac{\alpha+1}{\alpha+\beta+t}$ |
| Modelo de Tiempo Continuo  | $\lambda \sim \mathrm{Gamma}(r,\alpha)$       | $\lambda \mid t \sim \mathrm{Gamma}(r+1,\alpha + t)$      | $\mathbb{E}[\lambda \mid t] = \dfrac{r+1}{\alpha+t}$             |
| Modelo de Conteo           | $\lambda \sim \mathrm{Gamma}(r,\alpha)$       | $\lambda \mid x, t  \sim \mathrm{Gamma}(r+x,\ \alpha+t)$      | $\mathbb{E}[\lambda \mid x, t] = \dfrac{r+x}{\alpha+t}$             |
| Modelo de Elección Binaria | $\theta \sim \mathrm{Beta}(\alpha,\beta)$     | $\theta \mid x \sim \mathrm{Beta}(\alpha+x,\ \beta+m-x)$  | $\mathbb{E}[\theta \mid x] = \dfrac{\alpha+x}{\alpha+\beta+m}$   |

:::

-   Distribución *Beta*:

    $$f(x|\alpha,\beta) = \frac{x^{\alpha - 1}(1-x)^{\beta-1}}{B(\alpha,\beta)} \qquad \mathbb{E}(X) = \frac{\alpha}{\alpha + \beta} \qquad \mathbb{V}ar(X) = \frac{\alpha \beta}{(\alpha + \beta)^2 (\alpha + \beta + 1)} $$

-   Distribución *Gamma*:

$$f(x|r, \alpha) = \frac{\alpha^r x^{r-1} e^{-\alpha x}}{\Gamma(r)} \qquad \mathbb{E}(X) = \frac{r}{\alpha} \qquad \mathbb{V}ar(X) = \frac{r}{\alpha^2}$$

-   Función *Gamma*:

$$\Gamma(z) = \int_{0}^\infty t^{z-1} e^{-t} dt \qquad \Gamma(z+1) = z\Gamma(z) $$

-   Función *Beta*:
    $$B(\alpha,\beta) = \int_{0}^\infty t^{\alpha-1} (1-t)^{\beta-1} dt\qquad B(\alpha,\beta) = \frac{\Gamma(\alpha)\Gamma(\beta)}{\Gamma(\alpha + \beta)} $$
-   Tasa de Riesgo:

$$h(t) = \frac{f(t)}{1-F(t)} \qquad F(t) = 1- exp(-\int_{0}^{t} h(u)du) $$

-   Métricas de ajuste

    | Métrica de Error         | Métrica de Ajuste / Criterio de Información                         |
    |:-------------------------|:---------------------------------------------------------------------|
    | $MAE = \frac{1}{n}\sum_{i=1}^{n} \lvert y_i - \hat{y_i}\rvert$ | $MAPE = \frac{100}{n} \sum_{i=1}^{n} \left\lvert\frac{y_i - \hat{y_i}}{y_i}\right\rvert$ |
    | $MSE = \frac{1}{n}\sum_{i=1}^{n} (y_i - \hat{y_i})^2$ | $R^2 = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y_i})^2}{\sum_{i=1}^{n}(y_i - \bar{y})^2}$ |
    | $\chi^2 = \sum_{i=1}^{n} \frac{(y_i - \hat{y_i})^2}{\hat{y_i}}$ | $LR = 2(LL_{\text{NR}} - LL_{\text{R}}) \sim \chi^2$ |
    |  | $AIC = -2\ln(L(\hat{\theta})) + 2k$ |
    |  | $BIC = -2\ln(L(\hat{\theta})) + k\ln(n)$ |
